version: '3'
services:

    redis:
        image: redis
        restart: always

    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./mariadb:/var/lib/mysql
        ports:
            - "3307:3306" 

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        environment:
            MYSQL_USERNAME: root
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8001:80"
        links: 
            - mariadb

    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - "1080:1080"
