version: '3'
services:

    redis:
        image: redis

    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./mariadb:/var/lib/mysql
        ports:
            - 8000:80

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 8080:80

    mailcatcher:
        image: schickling/mailcatcher
        ports:
            - 1080:1080
